imports:
  - { resource: config.yml }

framework:
  profiler:
    only_exceptions: false
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true

monolog:
  handlers:
    console:
      bubble: false
      channels:
        - "!doctrine"
      type: console
      verbosity_levels:
        VERBOSITY_VERBOSE: INFO
        VERBOSITY_VERY_VERBOSE: DEBUG
    console_very_verbose:
      bubble: false
      channels:
        - doctrine
      type: console
      verbosity_levels:
        VERBOSITY_DEBUG: DEBUG
        VERBOSITY_VERBOSE: NOTICE
        VERBOSITY_VERY_VERBOSE: NOTICE
    main:
      level: debug
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      type: stream

services:
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaServerMockCommandsCollector:
    public: false
    tags: [{name: data_collector, template: '@Supla/Supla/supla-server-mock-data-collector.html.twig', id: 'supla.supla_server_mock_data_collector'}]

web_profiler:
  intercept_redirects: false
  toolbar: true
